language: ruby
cache:
  bundler: true
  yarn: true
env:
  global:
    - RAILS_ENV=test
    - MOZ_HEADLESS=1
services:
  - postgresql
  - xvfb
install:
  - travis_retry nvm install --lts
  - bundle
before_script:
  - bundle install --jobs=3 --retry=3
  - yarn
  - cp config/database.yml.travis config/database.yml
  - bundle exec rails db:create
  - bundle exec rails db:migrate
  - bundle exec rails db:schema:load
  - bundle exec rails webpacker:compile
  
script:
  - xvfb-run -a --server-args="-screen 0 1024x768x24" bundle exec rake
  - bundle exec rspec
  - bundle exec rubocop --require rubocop-rails
addons:
  firefox: latest